routes/web.php
<?php

use Illuminate\Http\Request;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', function () {
    $items = \App\Item::all();
    return view('home', ['items' => $items]);
})->middleware('auth');

Route::get('/home', 'HomeController@index');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/rents', 'RentController@test')->name('test')->middleware('auth');

Route::get('/admin/rents/generate-pdf','RentController@generatePDF');


Route::resource('rents', 'RentController')->middleware('auth');
Route::resource('items', 'ItemController')->middleware('auth');


Auth::routes();

app/Item.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Item extends Model
{
    protected $fillable = [
        'name',
        'description',
        'price',
        'quantity',
        'image'
    ];


    public function rents()
    {
        return $this->hasMany('\App\Rent');
    }
}

app/Models/Item.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Backpack\CRUD\CrudTrait;

class Item extends Model
{
    use CrudTrait;

    /*
    |--------------------------------------------------------------------------
    | GLOBAL VARIABLES
    |--------------------------------------------------------------------------
    */

    protected $table = 'items';
     protected $primaryKey = 'id';
    // public $timestamps = false;
    // protected $guarded = ['id'];
    protected $fillable = [
        'name',
        'description',
        'price',
        'quantity',
        'image'
    ];
    // protected $hidden = [];
    // protected $dates = [];

    /*
    |--------------------------------------------------------------------------
    | FUNCTIONS
    |--------------------------------------------------------------------------
    */

    /*
    |--------------------------------------------------------------------------
    | RELATIONS
    |--------------------------------------------------------------------------
    */

    /*
    |--------------------------------------------------------------------------
    | SCOPES
    |--------------------------------------------------------------------------
    */

    /*
    |--------------------------------------------------------------------------
    | ACCESORS
    |--------------------------------------------------------------------------
    */

    /*
    |--------------------------------------------------------------------------
    | MUTATORS
    |--------------------------------------------------------------------------
    */
}

app/Http/Controllers/ItemController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Item;

class ItemController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $items = Item::all();

        return view('items.index', compact('items'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('items.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'item_name' => 'required',
            'item_description' => 'required|max:255',
            'item_price' => 'integer',
            'item_quantity' => 'integer'
        ]);

        $item = new Item([
            'name' => $request->get('item_name'),
            'description' => $request->get('item_description'),
            'price' => $request->get('item_price'),
            'quantity' => $request->get('item_quantity')
        ]);

        $item->save();
        return redirect('/items')->with('success', 'Item has been added');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $item = Item::find($id);

        return view('items.show', compact('item'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $item = Item::find($id);

        return view('items.edit', compact('item'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'item_name' => 'required',
            'item_description' => 'required|max:255',
            'item_price' => 'integer',
            'item_quantity' => 'integer'
        ]);

        $item = Item::find($id);
        $item->name = $request->get('item_name');
        $item->description = $request->get('item_description');
        $item->price = $request->get('item_price');
        $item->quantity = $request->get('item_quantity');

        $item->save();
        return redirect('/items')->with('success', 'Item has been updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $item = Item::find($id);
        $item->delete();

        return redirect('/items')->with('success', 'Item has been deleted');
    }
}

resources/views/items/create.blade.php
@extends('layouts.app')

@section('content')
    <style>
        .uper {
            margin-top: 40px;
        }
    </style>
    <div class="card uper">
        <div class="card-header">
            Add Share
        </div>
        <div class="card-body">
            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div><br />
            @endif
            <form method="post" action="{{ route('items.store') }}">
                <div class="form-group">
                    @csrf
                    <label for="name">Item Name:</label>
                    <input type="text" class="form-control" name="item_name"/>
                </div>
                <div class="form-group">
                    <label for="description"> Item Description :</label>
                    <input type="text" class="form-control" name="item_description"/>
                </div>
                <div class="form-group">
                    <label for="price">Item Price :</label>
                    <input type="number" class="form-control" name="item_price"/>
                </div>
                <div class="form-group">
                    <label for="quantity">Item Quantity:</label>
                    <input type="number" class="form-control" name="item_quantity"/>
                </div>
                <button type="submit" class="btn btn-primary">Add</button>
            </form>
        </div>
    </div>
@endsection

resources/views/items/edit.blade.php
@extends('layouts.app')

@section('content')
    <style>
        .uper {
            margin-top: 40px;
        }
    </style>
    <div class="card uper">
        <div class="card-header">
            Edit Item
        </div>
        <div class="card-body">
            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div><br />
            @endif
            <form method="post" action="{{ route('items.update', $item->id) }}">
                @method('PATCH')
                @csrf
                <div class="form-group">
                    <label for="name">Item Name:</label>
                    <input type="text" class="form-control" name="item_name" value={{ $item->name }} />
                </div>
                <div class="form-group">
                    <label for="name">Item Description:</label>
                    <input type="text" class="form-control" name="item_description" value={{ $item->description }} />
                </div>
                <div class="form-group">
                    <label for="price">Item Price :</label>
                    <input type="text" class="form-control" name="item_price" value={{ $item->price }} />
                </div>
                <div class="form-group">
                    <label for="quantity">Item Quantity:</label>
                    <input type="text" class="form-control" name="item_quantity" value={{ $item->quantity }} />
                </div>
                <button type="submit" class="btn btn-primary">Update</button>
            </form>
        </div>
    </div>
@endsection

resources/views/items/homeCopy.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        {{--<div class="row justify-content-center">--}}
        {{--<div class="col-md-8">--}}
        {{--<div class="card">--}}
        {{--<div class="card-header">Dashboard</div>--}}

        {{--<div class="card-body">--}}
        {{--@if (session('status'))--}}
        {{--<div class="alert alert-success" role="alert">--}}
        {{--{{ session('status') }}--}}
        {{--</div>--}}
        {{--@endif--}}
        {{--<div class="links">--}}
        {{--@foreach ($items as $item)--}}
        {{--                                <br> <a href="{{ $item->name }}">{{ $item->name }}</a>--}}
        {{--<br> <a href="{{ route('items.update', $item->id) }}">{{ $item->name }}</a>--}}

        {{--<br> <img src="{{ $item->image }}" alt="Any alt text"/>--}}
        {{--<p><img src="{{ asset('/gfx/netgate.jpg') }}" /><p>--}}

        {{--@endforeach--}}
        {{--</div>--}}

        {{--</div>--}}
        {{--</div>--}}
        {{--</div>--}}
        {{--</div>--}}

        {{--<div class="row">--}}
        <div class="d-flex align-content-around flex-wrap">
            <div class="col-sm-6 col-md-4">
                <div class="thumbnail">
                    <div class="row">

                        @foreach($items as $item)
                            <img src="{{ $item->image }}" alt="Any alt text"/>
                            <div class="caption">
                                <h3><a href="{{ route('items.update', $item->id) }}">{{ $item->name }}</a></h3>
                                <p class="description">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolores
                                    error eum inventore officia quis quos totam! Asperiores deleniti, distinctio illum
                                    incidunt nulla officiis sssssssssssssssssssquas suscipit vitae? Magni necessitatibus repellendus
                                    voluptate!</p>
                                <div class="clearfix">
                                    <div class="pull-left price">{{$item->price}}</div>
                                    <a href="{{ route('items.update', $item->id) }}" class="btn btn-success pull-right"
                                       role="button">Details</a>
                                    @endforeach
                                </div>
                            </div>
                    </div>
                </div>
            </div>
        </div>

        <h1>Use Bootstrap's carousel to show multiple items per slide.</h1>
        <div class="row">
            <div class="col-md-12">
                <div class="carousel slide multi-item-carousel" id="theCarousel">
                    <div class="carousel-inner">
                        <div class="item active">
                            <div class="col-xs-4"><a href="#1"><img src="http://placehold.it/300/f44336/000000" class="img-responsive"></a></div>
                        </div>
                        <div class="item">
                            <div class="col-xs-4"><a href="#1"><img src="http://placehold.it/300/e91e63/000000" class="img-responsive"></a></div>
                        </div>
                        <div class="item">
                            <div class="col-xs-4"><a href="#1"><img src="http://placehold.it/300/9c27b0/000000" class="img-responsive"></a></div>
                        </div>
                        <div class="item">
                            <div class="col-xs-4"><a href="#1"><img src="http://placehold.it/300/673ab7/000000" class="img-responsive"></a></div>
                        </div>
                        <div class="item">
                            <div class="col-xs-4"><a href="#1"><img src="http://placehold.it/300/4caf50/000000" class="img-responsive"></a></div>
                        </div>
                        <div class="item">
                            <div class="col-xs-4"><a href="#1"><img src="http://placehold.it/300/8bc34a/000000" class="img-responsive"></a></div>
                        </div>
                        <!-- add  more items here -->
                        <!-- Example item start:  -->

                        <div class="item">
                            <div class="col-xs-4"><a href="#1"><img src="http://placehold.it/300/8bc34a/000000" class="img-responsive"></a></div>
                        </div>

                        <!--  Example item end -->
                    </div>
                    <a class="left carousel-control" href="#theCarousel" data-slide="prev"><i class="glyphicon glyphicon-chevron-left"></i></a>
                    <a class="right carousel-control" href="#theCarousel" data-slide="next"><i class="glyphicon glyphicon-chevron-right"></i></a>
                </div>
            </div>
        </div>
    </div>

    </div>
@endsection

resources/views/items/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="container-fluid" style="border:1px solid #cecece;">


        {{--<div class="row">--}}
            <br>
        <div class="d-flex align-content-around flex-wrap">
            <div class="col-sm-6 col-md-4">
                <div class="thumbnail">
                    <div class="row">

                        @foreach($items as $item)
                            <div>
                            <img src="{{ $item->image }}" alt="Any alt text"/>
                            <div class="caption">
                                {{--<h3><a href="{{ route('items.update', $item->id) }}">{{ $item->name }}</a></h3>--}}
                                {{--<p class="description">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolores--}}
                                    {{--error eum inventore officia quis quossadasdasd totam! Asperiores deleniti, distinctio illum--}}
                                    {{--incidunt nulla officiis sssssssssssssssssssquas suscipit vitae? Magni necessitatibus repellendus--}}
                                    {{--voluptate!</p>--}}
                                <p>{{$item->description}}</p>
                                <div class="clearfix">
                                    <div class="pull-left price">{{$item->price}} $</div>
                                    <a href="{{ route('items.update', $item->id) }}" class="btn btn-success pull-right"
                                       role="button">Detail</a>
                                </div>
                                    @endforeach
                                </div>
                            </div>
                    </div>
                </div>
            </div>
        </div>
        </div>
    </div>
@endsection

resources/views/items/order.blade.php
<div class="form-group">
    {{--<label for="title">Title</label>--}}
    <label for="title">Avaliable quantity : {{$item->quantity}}</label>

    @if ($errors->any())
        <ul>{!! implode('', $errors->all('<li style="color:red">:message</li>')) !!}</ul>
    @endif

    <input type="number" class="form-control" name="rent_quantity" id="quantity">
    <input type="number" class="form-control" name="rent_item" id="item" value="{{$item->id}}" hidden>
</div>

resources/views/items/rented.blade.php
@extends('layouts.app')

@section('content')
    <style>
        .uper {
            margin-top: 40px;
        }
    </style>
    <div class="uper">
        @if(session()->get('success'))
            <div class="alert alert-success">
                {{ session()->get('success') }}
            </div><br />
        @endif
        <table class="table table-striped">
            <thead>
            <tr>
                <td>ID</td>
                <td>Item Name</td>

                <td>Item Price</td>
                <td>Item Quantity</td>
                <td colspan="2">Action</td>

            </tr>
            </thead>
            <tbody>
            asdasdas
            </tbody>
        </table>
            @foreach($rents as $value)
{{--              {{$value->item->image}}--}}
            <br>
                <img src="{{$value->item->image }}" alt="Any alt text"/>
                <br>

                {{$value->quantity}}
            @endforeach
        <div>
@endsection

resources/views/items/show.blade.php
@extends('layouts.app')

@section('content')
    <style>
        .uper {
            margin-top: 40px;
        }
    </style>
    <div class="container">

    <div class="card border-secondary mb-3" style="max-width: 30rem;">
        <div class="card-header"><center>{{$item->name}}</center></div>
        <div class="card-body text-primary">
            <h5 class="card-title"><img src="{{ $item->image }}" alt="Any alt text"/></h5>
            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
            <p>{{$item->price}} $</p>
            <button class="btn btn-info" data-toggle="modal" data-target="#order">Rent</button>
            <a href="/" class="card-link">Go back </a>



            <div class="modal fade" id="order" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            <h4 class="modal-title" id="myModalLabel">New Category</h4>
                        </div>
                        <form action="{{route('rents.store')}}" method="post">
                            {{csrf_field()}}
                            <div class="modal-body">
                                @include('items.order')
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                <button type="submit" class="btn btn-primary">Save</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>



    </div>
@endsection